# Generated by Django 3.1.3 on 2022-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20220909_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votor',
            new_name='voter',
        ),
    ]
